obstacle_range: 2.5
raytrace_range: 4.0
footprint: [[0.535, 0.325], [0.535, -0.325],[-0.535, -0.325] , [-0.535, 0.325]]
# footprint: [[0.535, 0.315], [0.535, -0.315],[-0.535, -0.315] , [-0.535, 0.315]]

# footprint: [[0.6, 0.42], [0.6, -0.42],[-0.6, -0.42] , [-0.6, 0.42]]

#robot_radius: ir_of_robot
# inflation_radius: 0.3
# cost_scaling_factor: 5

observation_sources: laser_scan_rear laser_scan_front #point_cloud_sensor

laser_scan_rear:    {sensor_frame: base_laser_rear, data_type: LaserScan, topic: base_scan_rear, marking: true, clearing: true}
laser_scan_front:  {sensor_frame: base_laser_front, data_type: LaserScan, topic: base_scan_front, marking: true, clearing: true}


#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}