base_local_planner: "eband_local_planner/EBandPlannerROS"

controller_frequency: 40.0      # 20.0
controller_patience:  10.0      # 15.0

EBandPlannerROS:

  ## Common Parameters

  xy_goal_tolerance: 0.02 #Distance tolerance for reaching the goal pose ()

  yaw_goal_tolerance: 0.03 #Orientation tolerance for reaching the desired goal pose 

  rot_stopped_vel: 0.01 # Angular velocity lower bound that determines if the robot should stop to avoid limit-cycles or locks 

  trans_stopped_vel: 0.01 # Linear velocity lower bound that determines if the robot should stop to avoid limit-cycles or locks 

  ## Visualization Parameters

  marker_lifetime: 0.5 # Lifetime of eband visualization markers 

  ## Elastic Band Parameters

  eband_min_relative_overlap: 0.7 # Min distance that denotes connectivity between consecutive bubbles 

  eband_tiny_bubble_distance: 0.01 # Bubble geometric bound regarding tiny bubble distance 

  eband_tiny_bubble_expansion: 0.01 # Bubble geometric bound regarding tiny bubble expansion 

  eband_internal_force_gain: 1.00 # Force gain of forces between consecutive bubbles that tend to stretch the elastic band  (def: 1)

  eband_external_force_gain: 2.0 # Force gain of forces that tend to move the bubbles away from obstacles (def: 2)

  num_iterations_eband_optimization: 5 # Number of iterations for eband optimization  (def: 3)

  eband_equilibrium_approx_max_recursion_depth: 6 # Number of iterations for reaching the equilibrium between internal and external forces 

  eband_equilibrium_relative_overshoot: 0.75 # Maximum relative equlibrium overshoot 

  eband_significant_force_lower_bound: 0.15 # Minimum magnitude of force that is considered significant and used in the calculations 

  costmap_weight: 10.0 # Costmap weight factor used in the calculation of distance to obstacles 

  
  ## Trajectory Controller Parameters

  max_vel_lin: 9.0 # Maximum linear velocity 

  max_vel_th: 0.4 # Maximum angular velocity 

  min_vel_lin: 0.0 # Minimum linear velocity 

  min_vel_th: 0.0 # Minimum angular velocity 

  min_in_place_vel_th: 0.0 # Minimum in-place angular velocity 

  in_place_trans_vel: 0.0 # Minimum in place linear velocity 

  k_prop: 4.0 # Proportional gain of the PID controller 

  k_damp: 3.5 # Damping gain of the PID controller 

  Ctrl_Rate: 30.0 # Control rate 

  max_acceleration: 2.5 # Maximum allowable acceleration 

  virtual_mass: 0.75 # Virtual mass 

  max_translational_acceleration: 2.0 # Maximumk linear acceleration 

  max_rotational_acceleration: 1.5 # Maximum angular acceleration 

  rotation_correction_threshold: 1.0   # Rotation correction threshold 

  differential_drive: false # Denotes whether to use the differential drive mode 

  bubble_velocity_multiplier: 2.0 # Multiplier of bubble radius 

  rotation_threshold_multiplier: 1.0 # Multiplier of rotation threshold 

  disallow_hysteresis: False # Determines whether to try getting closer to the goal, in case of going past the tolerance 
