local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  transform_tolerance: 2
  update_frequency: 15.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05

  inflation_layer:
    cost_scaling_factor: 5.0
    inflation_radius: 0.4