base_local_planner: "teb_local_planner/TebLocalPlannerROS"

controller_frequency: 30.0      # 20.0
controller_patience:  15.0      # 15.0

TebLocalPlannerROS:

 odom_topic: odom
 map_frame: map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.4  
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
 allow_init_with_backwards_motion: true
    
 # Robot
         
 max_vel_x: 0.5
 max_vel_y: 0.5
 max_vel_x_backwards: 0.4
 max_vel_theta: 0.3
 acc_lim_x: 0.9
 acc_lim_y: 0.9
 acc_lim_theta: 0.9
 min_turning_radius: 0.0
# footprint: [[0.535, 0.315], [0.535, -0.315],[-0.535, -0.315] , [-0.535, 0.315]]

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
  type: "line"
  #  radius: 0.2 # for type "circular"
  line_start: [-0.22, 0.0] # for type "line"
  line_end: [0.22, 0.0] # for type "line"
  #  front_offset: 0.2 # for type "two_circles"
  #  front_radius: 0.2 # for type "two_circles"
  #  rear_offset: 0.2 # for type "two_circles"
  #  rear_radius: 0.2 # for type "two_circles"
  #vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.03
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.33
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 4.0
 weight_acc_lim_y: 1.0
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1 # was 1000 for car-like robots, decreased fiven suggestiond for holonomic robots in ROS wiki
 weight_kinematics_forward_drive: 0.001
 weight_kinematics_turning_radius: 0.001
 weight_optimaltime: 0.01
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet
 
 
 
 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 3
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False