theme: jekyll-theme-leap-day
title: [Mobile Manipulation Tutorial]
description: [Additional resources for the (journal name tbd) Mobile Manipulation Tutorial (MoManTu)]
github:
  is_project_page: false