controller_list:
  - name: fake_l_arm_controller
    joints:
      - l_arm_j1_joint
      - l_arm_j2_joint
      - l_arm_j3_joint
      - l_arm_j4_joint
      - l_arm_j5_joint
      - l_arm_j6_joint
      - l_arm_j7_joint
  - name: fake_r_arm_controller
    joints:
      - r_arm_j1_joint
      - r_arm_j2_joint
      - r_arm_j3_joint
      - r_arm_j4_joint
      - r_arm_j5_joint
      - r_arm_j6_joint
      - r_arm_j7_joint
  - name: fake_l_gripper_controller
    joints:
      - l_gripper_thumb_joint
  - name: fake_r_gripper_controller
    joints:
      - r_gripper_thumb_joint